### ISSUE TITLE
a bug in vqvae training

### ISSUE THREAD

**Issue by Zbozhou** [wzzheng/OccSora#1]
Thanks for your excellent work, but it seems a bug here.
https://github.com/wzzheng/OccSora/blob/main/model/VAE/vae_2d_resnet.py
![image](https://github.com/wzzheng/OccSora/assets/94776245/c9ca7d7c-d2e2-4b80-b72d-287256506e88)

**Comment by LeningWang** [comment]
Please tell me the specific error information.

**Comment by jjlinghu** [comment]
> Please tell me the specific error information.

Actually, there is an unmatched right parenthesis ')'  in line 283.

**Comment by LeningWang** [comment]
Thanks, we'll check, probably because some print breakpoints didn't clear when we removed them.
