### ISSUE TITLE
Where to obtain pickle files?

### ISSUE THREAD

**Issue by bian-hengwei** [wzzheng/OccSora#11]
I noticed that preprocessed pickle files are needed for vqvae training. I wonder where I can obtain the following files:
nuscenes_infos_train_temporal_v3_scene.pkl
nuscenes_infos_val_temporal_v3_scene.pkl

The link provided in README.md redirects to TPVFormer, which provides pkl files but has a different format.

Thank you.

**Comment by LeningWang** [comment]
sorry, you can fine this file in OccWorld https://github.com/wzzheng/OccWorld
