### ISSUE TITLE
About pretrained model 

### ISSUE THREAD

**Issue by jjlinghu** [wzzheng/OccSora#3]
Hi, thanks for your great work! 
Could you please provide the pre-trained model as the [OccWorld](https://cloud.tsinghua.edu.cn/d/ff4612b2453841fba7a5/)? In fact, I don't have the enough resources to repeat the train pipeline.
Thanks in advance!

**Comment by LeningWang** [comment]
Of course, we can provide pre-training model, but the pre-training model file is large, can not be directly uploaded, need to through the cloud storage, you can leave the mailbox first, we send through the mailbox

**Comment by jjlinghu** [comment]
This is my mailbox: lhjj@mail.ustc.edu.cn. 
I'm not sure if the school email can receive large files, but we can give it a try.
Thanks again!

**Comment by LeningWang** [comment]
![image](https://github.com/wzzheng/OccSora/assets/74409418/5ff0ce80-76a4-43d6-a733-0820f164b979)
I have sent you the email of the model check point, please check it.

**Comment by jjlinghu** [comment]
Hi! I have accepted the files, thanks a lot!

**Comment by yanghu819** [comment]
great work，I also need the checkpoints, my email is huyangtorus@gmail.com
