### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/samplees_array.npy 

### ISSUE THREAD

**Issue by zengstrive** [wzzheng/OccSora#4]
How to get this file and what are the steps to train it.

**Comment by zengCSDN** [comment]
How do I get this file?

**Comment by LeningWang** [comment]
Please delate out during the first phase of training.
This is used visually after the second phase of training: python sample.py --model DiT-XL/2 --image-size 256 --ckpt "/results/001-DiT-XL-2/checkpoints/1200000.pt" obtained samples_array.npy, enter it here, and then execute: python visualize_demo.py --py-config config/train_vqvae.py --work-dir out/vqvae
