### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by skskgrowl** [wzzheng/OccSora#5]
Hi, thanks for your great work!
Could you please provide the pre-trained model? my mailbox: songk9@mail2.sysu.edu.cn
Thanks in advance!

**Comment by LeningWang** [comment]
have a try https://bhpan.buaa.edu.cn/link/AAE83D367BA6EA456DBAD6CADD51221991

文件名：epoch_125.pth

有效期限：2024-07-20 11:57

提取码：vnW7

**Comment by skskgrowl** [comment]
Thanks! Can you give me the pretrained models of the first stage?

**Comment by LeningWang** [comment]
this is the first stage

**Comment by skskgrowl** [comment]
Thanks!

**Comment by Orbis36** [comment]
The link is expired @LeningWang

**Comment by panbaojing** [comment]
> have a try https://bhpan.buaa.edu.cn/link/AAE83D367BA6EA456DBAD6CADD51221991
> 
> 文件名：epoch_125.pth
> 
> 有效期限：2024-07-20 11:57
> 
> 提取码：vnW7

网盘地址已失效，能否重新提供？

**Comment by maeismaeis** [comment]
> > have a try https://bhpan.buaa.edu.cn/link/AAE83D367BA6EA456DBAD6CADD51221991
> > 文件名：epoch_125.pth
> > 有效期限：2024-07-20 11:57
> > 提取码：vnW7
> 
> 网盘地址已失效，能否重新提供？

Apologies for the long wait. Here is the link to the checkpoint: https://bhpan.buaa.edu.cn/link/AA742CFFFB6AD846E889A4CAFF7BE09828 , password：uJ34. If you encounter any issues, please feel free to contact me via email at [leningwang@buaa.edu.cn](mailto:leningwang@buaa.edu.cn). You are also welcome to check out our new project at https://github.com/wzzheng/Stag. Thank you!

**Comment by 3340388133** [comment]
> > > 试试https://bhpan.buaa.edu.cn/link/AAE83D367BA6EA456DBAD6CADD51221991
> > > 文件名：epoch_125.pth
> > > 有效期限：2024-07-20 11:57
> > > 提取码：vnW7
> > 
> > 
> > 网盘地址已失效，能否重新提供？
> 
> 久等了，非常抱歉。这是检查点的链接：https://bhpan.buaa.edu.cn/link/AA742CFFFB6AD846E889A4CAFF7BE09828，密码：uJ34。如果您遇到任何问题，请随时通过电子邮件联系我：[leningwang@buaa.edu.cn](mailto:leningwang@buaa.edu.cn)。也欢迎您查看我们的新项目：https://github.com/wzzheng/Stag。谢谢！

网盘地址失效了 可以求一份吗 谢谢
