### ISSUE TITLE
tokenizer效果很差？

### ISSUE THREAD

**Issue by XPLearner** [wzzheng/OccSora#8]
Table 1: The quantitative analysis of 4D occupancy reconstruction. Despite a compression rate 32
times greater than OccWorld, OccSora maintains over half of its reconstruction accuracy compared
to OccWorld.
这里面看指标，似乎比baseline要差好多倍？ 是我理解错了吗

**Comment by wzzheng** [comment]
没有理解错，确实比OccWorld精度上要差不少，但是压缩率是OccWorld的32倍。
